### ISSUE TITLE
Targethud not working

### ISSUE THREAD

**Issue by CloudyWhale** [WYSI-Foundation/LiquidBouncePlus#116]
So I enabled targethud in the hud editor and it only shows when I open chat or when I go into the gui editor and It shows me. I tried opening chat in a fight and nothing changed, still showing me.
<img src="https://i.ibb.co/F5kD8F5/eeeee.png"></img>

**Comment by broidfklol** [comment]
shut the fuck up this fucking github is about updates

**Comment by broidfklol** [comment]
Hello, this is a really long paragraph so why not put it
in a code form?

I'm casually talking about how long this thing is,
and I know, it's weird. I have never constructed 
a paragraph this long, and It's pretty amazing
that I have this ability to make very long paragraphs.

I could write a whole book right now, with sentences
containing figures of speech, since that's what makes
stories fun.

It's taking me so long to make this thing, so I should
probably stop. Just kidding. I won't stop. Stopping this
would be terrible since my plan is to write the longest
paragraph sent in a text message via Discord.

I don't even know why I am creating these types of things,
but it just seems fun to me. These types of text just
satisfy my time.

I'd consider this spam, but I'll take the risk of getting 
banned on this server. If a moderator sees this then I'm
banned from this server, and PERMANENT ban. But if a moderator
doesn't see this, then I'd be happy to see this message pass
by.

I'll check for grammar and spelling errors, since some 
people would probably decide to read this horrible text
that I constructed.

I'll save this text file, so I'll continue to annoy servers
or people in DMs. I'd like to see their reaction to this
ridiculously long paragraph.

Also, I didn't do englishman's job today. It isn't even 
related to an animation, plus, I'm not an animator.
This is not even a video long.

And if I reach my goal to write the longest paragraph
that was sent via message, then I'll spam my friends
with this, and they'll probably block me because I'm
annoying them. It's a risk to do it.

And, please don't copy-paste this, because I don't like
copy-pasting. I'd appreciate it if you don't copy-paste.

If this doesn't fit in discord, then I'll remove some
parts.

I know, you won't read this because this is long,
but I spent my time on it.

But if you say it sucks, then I'll spam you with it
you stupid little piece of sh--

Sorry for that.

Anyways, let's get back to writing this ridiculously
long text.

I don't even know why I spent so much time creating
this, when you don't even read it. So I'd consider
reading it, or else this is was just a waste of time.

Also, don't spam me with this thing that I wrote,
because... that's annoying.

While I'm writing this, I'm listening to some
undertale music. It's helping me write my paragraphs,
and some people on discord are also helping me by
sending messages about a certain topic, and I'm
putting it here.

I'd want to reach atleast 105 lines, because why
not?

And while I was writing this, I repeatedly kept
spamming and I received my final warning. If I
get banned, then I don't even care. I could just
send it to other servers anyway.

Mod, if you see this, ban me, because as I said, it 
was a risk to send this into Discord.

This has 88 lines. I'm planning to add more.

Thank you for reading this ridiculously long text.

**Comment by exit-scammed** [comment]
turn off displaywhenchat.

**Comment by CloudyWhale** [comment]
Still not working.

**Comment by CloudyWhale** [comment]
Maybe it is happening because I did not manually build it and I got it from the releases page?

**Comment by exit-scammed** [comment]
we don't support any build that does not come from the release page.

**Comment by CloudyWhale** [comment]
I was using the one from the release page

**Comment by CloudyWhale** [comment]
I was saying maybe the issue is that I was using a version from the releases page

**Comment by exit-scammed** [comment]
do you have this issue with other targethud styles? try turning on/off killaura and teleportaura may help.

**Comment by CloudyWhale** [comment]
I am not using killaura or teleportaura and I have this issue with all styles

**Comment by CloudyWhale** [comment]
I am on kde plasma desktop and endeavor OS (based on arch) and I am using default minecraft launcher

**Comment by exit-scammed** [comment]
just checked the latest release build and its working normally (the displaywhenchat option). i dont really know what caused it.

**Comment by exit-scammed** [comment]
nvm its supposed to work like that.

**Comment by CloudyWhale** [comment]
Then how do I show my enemies health?

**Comment by exit-scammed** [comment]
i may fix this later.
